export const ROLES = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  PHARMACY_INVENTORY: 'PHARMACY_INVENTORY',
  DIAGNOSTICS: 'DIAGNOSTICS',
  FRONT_DESK: 'FRONT_DESK',
  NURSE: 'NURSE',
  REVENUE_OFFICE: 'REVENUE_OFFICE',
  BACK_OFFICE_FINANCE: 'BACK_OFFICE_FINANCE',
  PATIENT: 'PATIENT',
  HR: 'HR',
  MAINTENANCE: 'maintenance',
  EMERGENCY: 'emergency'
};
